version: 2.1
jobs:
  build-job:
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  deploy-job:
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run:
          name: "GIT config"
          command: |
            git config user.email "${CIRCLE_PROJECT_USERNAME}@users.noreply.github.com"
            git config user.name "${CIRCLE_PROJECT_USERNAME}"
      - add_ssh_keys:
          fingerprints:
            - "68:f3:a3:4e:05:7d:f8:d5:86:e6:88:3c:ab:cc:b5:b8"
      - run: npm run deploy

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: main
